// The ?v=1788672202888 suffixes are rewritten to the publish timestamp by
// publish.js on every publish, so a browser that cached the previous pair of
// files always fetches the fresh ones instead of mixing old logic with new
// data (or vice versa).
import {
  ABILITIES,
  SKILLS,
  CARRY_LOCATIONS,
  carryLocation,
} from './game-data.js?v=1788672202888'
import {
  abilityMod,
  armourClass,
  attackDamage,
  attackToHit,
  consumables,
  deathStatus,
  effectiveSpeed,
  encumbrance,
  heavyDisadvantage,
  initiative,
  itemWeight,
  passivePerception,
  profBonus,
  recoveryDetail,
  recoveryHours,
  saveBonus,
  signed,
  skillBonus,
  stabiliseDC,
  unarmedStrike,
  xpProgress,
  xpTotal,
} from './character-lib.js?v=1788672202888'

const $ = (id) => document.getElementById(id)

// Tiny DOM builder — no framework needed for a read-only page.
function el(tag, attrs = {}, children = []) {
  const node = document.createElement(tag)
  for (const [k, v] of Object.entries(attrs)) {
    if (v === null || v === undefined || v === false) continue
    if (k === 'class') node.className = v
    else if (k === 'html') node.innerHTML = v
    else node.setAttribute(k, v)
  }
  for (const child of [].concat(children)) {
    if (child === null || child === undefined || child === false) continue
    node.appendChild(typeof child === 'string' ? document.createTextNode(child) : child)
  }
  return node
}

const card = (title, subtitle, bodyChildren, accent) =>
  el('section', { class: `card${accent ? ' accent-' + accent : ''}` }, [
    el('h2', {}, [title, subtitle ? el('span', { class: 'sub' }, subtitle) : null]),
    el('div', { class: 'body' }, bodyChildren),
  ])

const tile = (label, value, foot, tone) =>
  el('div', { class: 'tile' }, [
    el('div', { class: 'label' }, label),
    el('div', { class: `value${tone ? ' tone-' + tone : ''}` }, String(value)),
    foot ? el('div', { class: 'foot' }, foot) : null,
  ])

async function main() {
  let data
  try {
    const res = await fetch('./character.json', { cache: 'no-store' })
    if (!res.ok) throw new Error('not found')
    data = await res.json()
  } catch {
    renderError()
    return
  }
  if (!data || !data.character) {
    renderError()
    return
  }
  render(data.character, data.publishedAt)
}

function renderError() {
  document.title = 'Character sheet'
  $('app').appendChild(
    el('div', { class: 'error-box' }, [
      el('strong', {}, 'Nothing published yet.'),
      el('p', {}, 'Ask the player to click "Publish for DM" on their sheet.'),
    ]),
  )
}

function render(c, publishedAt) {
  document.title = `${c.name || 'Character'} — read-only sheet`
  const app = $('app')
  app.innerHTML = ''

  app.appendChild(
    el('div', { class: 'banner' }, [
      '👁 Read-only — shared by the player.',
      publishedAt
        ? el('span', {}, `Last updated ${new Date(publishedAt).toLocaleString()}`)
        : null,
    ]),
  )

  // Several cards return null when a section is empty (no resources, no
  // spells yet, no features written) — skip those rather than handing
  // appendChild something that isn't a node.
  const append = (node) => node && app.appendChild(node)

  append(header(c))
  append(statRow(c))
  append(abilitiesCard(c))
  append(deathSaveCard(c))
  append(el('div', { class: 'two-col' }, [savesCard(c), skillsCard(c)]))
  append(attacksCard(c))
  append(encumbranceCard(c))
  append(inventoryCard(c))
  append(consumablesCard(c))
  append(vitalsCard(c))
  append(resourcesCard(c))
  append(spellsCard(c))
  append(xpCard(c))
  append(featuresCard(c))
  append(el('footer', { class: 'note' }, 'Generated by the player’s character sheet app.'))
}

function header(c) {
  const sub = [c.race, c.klass && `${c.klass} ${c.level}`, c.background, c.alignment, c.deity]
    .filter(Boolean)
    .join(' · ')
  return el('div', { class: 'header' }, [
    el('h1', {}, c.name || 'Unnamed'),
    el('div', { class: 'sub' }, sub || 'No details yet'),
  ])
}

function statRow(c) {
  const ac = armourClass(c)
  const init = initiative(c)
  const pp = passivePerception(c)
  const speed = effectiveSpeed(c)
  const enc = speed.enc
  return el('div', { class: 'stat-row' }, [
    tile('AC', ac.value),
    tile('Initiative', signed(init.value)),
    tile('Proficiency', signed(profBonus(c))),
    tile('Passive Perception', pp.value),
    tile('Speed', `${speed.value} ft`, enc.over ? 'over capacity' : null, enc.over ? 'bad' : null),
    tile('HP', `${c.hp?.current ?? 0}/${c.hp?.max ?? 0}`, null, (c.hp?.current ?? 0) < 1 ? 'bad' : null),
    tile('Carried', `${enc.carried}/${enc.capacity} lb`, null, enc.over ? 'bad' : null),
    tile('XP', xpTotal(c).value.toLocaleString(), `level ${c.level}`),
  ])
}

function abilitiesCard(c) {
  const grid = el(
    'div',
    { class: 'grid-6' },
    ABILITIES.map((a) => {
      const m = abilityMod(c, a.key)
      return el('div', { class: 'ability' }, [
        el('div', { class: 'short' }, a.short),
        el('div', { class: 'score' }, String(c.abilities?.[a.key] ?? 10)),
        el('div', { class: 'mod' }, signed(m)),
      ])
    }),
  )
  return card('Ability scores', 'Long rests do not restore ability damage', [grid])
}

function savesCard(c) {
  const rows = ABILITIES.map((a) => {
    const s = saveBonus(c, a.key)
    const prof = c.saves?.[a.key]?.prof
    return el('div', { class: 'row' }, [
      prof ? el('span', { class: 'chip prof' }, '●') : el('span', { class: 'chip' }, ' '),
      el('span', { class: 'name' }, a.label),
      el('span', { class: 'bonus' }, signed(s.value)),
    ])
  })
  return card('Saving throws', null, [el('div', { class: 'row-list' }, rows)])
}

function skillsCard(c) {
  const rows = SKILLS.map((s) => {
    const b = skillBonus(c, s.key)
    const entry = c.skills?.[s.key] || {}
    const marks = []
    if (entry.expertise) marks.push(el('span', { class: 'chip expertise' }, 'E'))
    else if (entry.prof) marks.push(el('span', { class: 'chip prof' }, 'P'))
    return el('div', { class: 'row' }, [
      ...marks,
      el('span', { class: 'name' }, s.label),
      el('span', { class: 'bonus' }, signed(b.value)),
    ])
  })
  return card('Skills', null, [el('div', { class: 'row-list' }, rows)])
}

function attacksCard(c) {
  const attacks = c.attacks || []
  const unarmed = unarmedStrike(c)
  const rows = attacks.map((a) => {
    const hit = attackToHit(c, a)
    const dmg = attackDamage(c, a)
    const disadv = heavyDisadvantage(c, a)
    return el('tr', {}, [
      el('td', {}, [a.name || '—', disadv ? el('div', { class: 'muted' }, 'disadvantage (Heavy + Small)') : null]),
      el('td', {}, signed(hit.value)),
      el('td', {}, dmg.value),
      el('td', {}, a.damageType || ''),
      el('td', { class: 'muted' }, a.notes || ''),
    ])
  })
  const table = el('div', { class: 'table-wrap' }, [
    el('table', {}, [
      el('thead', {}, el('tr', {}, ['Name', 'To hit', 'Damage', 'Type', 'Notes'].map((h) => el('th', {}, h)))),
      el('tbody', {}, rows),
    ]),
  ])
  return card('Attacks', null, [
    table,
    el('p', { class: 'muted', style: 'margin-top:8px;font-size:12px' }, [
      `Unarmed strike (${c.size}): ${unarmed.damage} bludgeoning.`,
    ]),
  ])
}

function encumbranceCard(c) {
  const e = encumbrance(c)
  const pct = e.capacity > 0 ? Math.min(100, (e.carried / e.capacity) * 100) : 0
  const tone = e.over ? 'bad' : pct > 75 ? 'warn' : 'good'
  return card('Encumbrance', `${e.carried} / ${e.capacity} lb`, [
    el('div', { class: 'bar-track' }, [
      el('div', { class: `bar-fill ${tone}`, style: `width:${pct}%` }),
      el('div', { class: 'bar-label' }, `${e.carried} lb`),
    ]),
    el('p', { class: 'muted', style: 'margin-top:8px;font-size:12px' }, [
      `STR ${c.abilities?.str} × 15 = ${e.capacity} lb capacity. `,
      e.over ? 'Over capacity — push/drag/lift only, speed 5 ft.' : `${e.remaining} lb of headroom.`,
    ]),
  ], e.over ? 'danger' : null)
}

function inventoryCard(c) {
  const items = c.inventory || []
  const rows = items.map((i) => {
    const loc = carryLocation(i.location)
    const flags = []
    if (i.magicArmour) flags.push('magic armour')
    if (i.consumable) flags.push('consumable')
    return el('tr', {}, [
      el('td', {}, i.name || '—'),
      el('td', {}, String(i.qty ?? 0)),
      el('td', {}, `${itemWeight(i)} lb`),
      el('td', { class: loc.carried ? '' : 'muted' }, loc.label + (loc.carried ? '' : ' (not carried)')),
      el('td', { class: 'muted' }, [flags.join(', '), i.notes ? (flags.length ? ' — ' : '') + i.notes : ''].join('')),
    ])
  })
  const table = el('div', { class: 'table-wrap' }, [
    el('table', {}, [
      el('thead', {}, el('tr', {}, ['Item', 'Qty', 'Weight', 'Where', 'Notes'].map((h) => el('th', {}, h)))),
      el('tbody', {}, rows.length ? rows : [el('tr', {}, el('td', { colspan: 5, class: 'muted' }, 'Nothing here.'))]),
    ]),
  ])
  return card('Inventory', `${items.length} items`, [table])
}

function consumablesCard(c) {
  const items = consumables(c)
  if (items.length === 0) return card('Consumables', null, [el('p', { class: 'muted' }, 'Nothing flagged as a consumable.')])
  const tiles = items.map((i) => tile(i.name || 'Item', i.qty ?? 0, carryLocation(i.location).label))
  return card('Consumables', 'If it is not on the sheet, they do not have it', [
    el('div', { class: 'stat-row' }, tiles),
  ])
}

function vitalsCard(c) {
  const hd = c.hitDice || {}
  const remaining = Math.max(0, (hd.total ?? 0) - (hd.spent ?? 0))
  return card('Hit points & hit dice', null, [
    el('div', { class: 'stat-row' }, [
      tile('HP', `${c.hp?.current ?? 0}/${c.hp?.max ?? 0}`, c.hp?.temp ? `+${c.hp.temp} temp` : null, (c.hp?.current ?? 0) < 1 ? 'bad' : null),
      tile('Hit dice', `${remaining}/${hd.total ?? 0}`, hd.die || ''),
    ]),
  ])
}

function resourcesCard(c) {
  const resources = c.resources || []
  if (resources.length === 0) return null
  const rows = resources.map((r) =>
    el('div', { class: 'row' }, [
      el('span', { class: 'name' }, [
        r.name || 'Resource',
        r.notes ? el('div', { class: 'muted', style: 'font-size:11px' }, r.notes) : null,
      ]),
      el('span', { class: 'bonus', style: 'width:auto' }, `${r.current ?? 0}/${r.max ?? 0} ${r.unit || ''}`),
    ]),
  )
  return card('Class resources', null, [el('div', { class: 'row-list' }, rows)])
}

function spellsCard(c) {
  const slots = c.spellSlots || []
  const prepared = c.preparedSpells || []
  if (slots.length === 0 && prepared.length === 0) return null
  const slotRows = slots.map((s) => {
    const used = s.used ?? 0
    const max = s.max ?? 0
    const pips = Array.from({ length: max }, (_, i) =>
      el('div', { class: `pip${i < max - used ? ' filled' : ''}` }),
    )
    return el('div', { class: 'row' }, [
      el('span', { class: 'name' }, `Level ${s.level}`),
      el('div', { class: 'pips' }, pips),
    ])
  })
  const prepList = prepared.length
    ? el('div', { class: 'row-list', style: 'margin-top:8px' }, prepared.map((s) =>
        el('div', { class: 'row' }, [el('span', { class: 'name' }, `${s.name || 'Spell'}`), el('span', { class: 'muted' }, `lvl ${s.level}`)]),
      ))
    : null
  return card('Spells', null, [el('div', { class: 'row-list' }, slotRows), prepList])
}

function xpCard(c) {
  const prog = xpProgress(c)
  const pct = prog.pct
  return card('Experience', `${prog.xp.toLocaleString()} XP · level ${c.level}`, [
    el('div', { class: 'bar-track' }, [
      el('div', { class: `bar-fill ${prog.readyToLevel ? 'warn' : 'good'}`, style: `width:${pct}%` }),
    ]),
    el('p', { class: 'muted', style: 'margin-top:8px;font-size:12px' }, [
      prog.nextThreshold === null
        ? 'Level 20 — maximum.'
        : `${prog.toNext.toLocaleString()} XP to level ${prog.level + 1} at ${prog.nextThreshold.toLocaleString()}.`,
    ]),
  ])
}

function deathSaveCard(c) {
  const ds = c.deathState || {}
  if (!ds.down && !ds.stabilised && !ds.dead) {
    return card('Death Save Land', null, [el('div', { class: 'death-banner calm' }, 'Not down.')])
  }
  if (ds.dead) {
    return card('Death Save Land', null, [el('div', { class: 'death-banner dead' }, 'DEAD')], 'danger')
  }
  if (ds.down) {
    const st = deathStatus(ds)
    const dc = stabiliseDC(st.failures)
    return card('Death Save Land', `${st.pending} save(s) pending`, [
      el('div', { class: 'death-banner warn' }, [
        el('p', {}, `Below 1 HP. ${st.successes}/3 successes, ${st.failures}/3 failures.`),
        el('p', {}, `Stabilise DC ${dc}.`),
      ]),
    ], 'danger')
  }
  // stabilised
  const hours = recoveryHours(ds.stabilisedFailures ?? 0)
  return card('Death Save Land', 'Stabilised', [
    el('div', { class: 'death-banner ok' }, [
      el('p', {}, `Stabilised at 1 HP with ${ds.stabilisedFailures ?? 0} failed save(s).`),
      el('p', {}, `${hours} hours out of action — ${recoveryDetail(ds.stabilisedFailures ?? 0)}`),
    ]),
  ])
}

function featuresCard(c) {
  const t = c.text || {}
  const blocks = [
    ['Class features', t.features],
    ['Racial traits', t.traits],
    ['Background', t.backgroundText],
  ].filter(([, v]) => v && v.trim())
  if (blocks.length === 0) return null
  return card('Features & traits', null, blocks.map(([label, body]) =>
    el('div', { style: 'margin-bottom:10px' }, [
      el('div', { class: 'label', style: 'font-size:10px;text-transform:uppercase;color:rgba(246,241,229,.4);margin-bottom:2px' }, label),
      el('div', { class: 'text-block' }, body),
    ]),
  ))
}

main()
